### PR TITLE
fix fastboot support

### LINKED ISSUE #50: fastboot support
I see you have some fastboot commits recently, but from what I'm seeing, it's not quite there yet. I'm getting:
```
There was an error running your app in fastboot. More info about the error: 
 ReferenceError: document is not defined
```
from https://github.com/null-null-null/ember-keyboard/blob/master/addon/services/keyboard.js#L40

which is run because of https://github.com/null-null-null/ember-keyboard/blob/master/addon/mixins/ember-keyboard.js#L14

which is probably run because of https://github.com/null-null-null/ember-keyboard/blob/master/addon/initializers/ember-keyboard-first-responder-inputs.js#L10-L11

Is this an inherit issue with the addon, or is it because I'm doing something I shouldn't during fastboot?

### PR DESCRIPTION
**Pull request by kellyselden**
Resolves #50

Curious what you think of this? It allows the fastboot process to continue. Without it, fastboot fails.

### CODE REVIEW

**Comment by null-null-null** [comment]
This looks good to me. If you feel like it's ready to merge, I'll pull it right in.

**Comment by kellyselden** [comment]
Alright, I tested this sufficiently in my app. I believe it's good to go!

**Comment by null-null-null** [comment]
Thanks, @kellyselden! Just published this under `v2.1.4`.

**Comment by kellyselden** [comment]
Thank you!

**Pull request merged**
