### PR TITLE
Add Slash and Backspace to default keyMap.

### PR DESCRIPTION
**Pull request by blimmer**
Was trying to toggle a keyboard shortcut helper with `?`, and noticed
that key `191` (`/` or `Shift+/`) wasn't wired up.

### CODE REVIEW

**Comment by null-null-null** [comment]
Good catch, but looks like this should actually be "Slash": https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

**Comment by null-null-null** [comment]
Looks like it's also missing "Backspace". I'm gonna comb over these and see what else needs to get filled in.

**Comment by null-null-null** [comment]
So it looks like "Backspace" and "Slash" are the two big ones. If you want to add "Backspace", it's keyCode is 8.

**Comment by blimmer** [comment]
updated and added! cc @H-Bomba

**Comment by blimmer** [comment]
No problem - @H-Bomba found this! ember-keyboard has one-upped our app for power users 😄

**Comment by null-null-null** [comment]
New release out for y'all: `2.0.0-beta3`

**Pull request merged**
